# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Ingredients
Ingredient.create(name: "Lemon")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Mint leaves")
Ingredient.create(name: "Light rum")
Ingredient.create(name: "Applejack")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Dark rum")
Ingredient.create(name: "Sweet Vermouth")
Ingredient.create(name: "Strawberry schnapps")
Ingredient.create(name: "Scotch")
Ingredient.create(name: "Apricot brandy")
Ingredient.create(name: "Triple sec")
Ingredient.create(name: "Southern Comfort")
Ingredient.create(name: "Orange bitters")
Ingredient.create(name: "Brandy")
Ingredient.create(name: "Lemon vodka")
Ingredient.create(name: "Blended whiskey")
Ingredient.create(name: "Dry Vermouth")
Ingredient.create(name: "Amaretto")
Ingredient.create(name: "Tea")
Ingredient.create(name: "Champagne")
Ingredient.create(name: "Coffee liqueur")
Ingredient.create(name: "Bourbon")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Añejo rum")
Ingredient.create(name: "Bitters")
Ingredient.create(name: "Sugar")
Ingredient.create(name: "Kahlua")
Ingredient.create(name: "demerara Sugar")
Ingredient.create(name: "Dubonnet Rouge")
Ingredient.create(name: "Watermelon")
Ingredient.create(name: "Lime juice")
Ingredient.create(name: "Irish whiskey")
Ingredient.create(name: "Apple brandy")
Ingredient.create(name: "Carbonated water")
Ingredient.create(name: "Cherry brandy")
Ingredient.create(name: "Creme de Cacao")
Ingredient.create(name: "Grenadine")
Ingredient.create(name: "Port")
Ingredient.create(name: "Coffee brandy")
Ingredient.create(name: "Red wine")
Ingredient.create(name: "Rum")
Ingredient.create(name: "Grapefruit juice")
Ingredient.create(name: "Ricard")
Ingredient.create(name: "Sherry")
Ingredient.create(name: "Cognac")
Ingredient.create(name: "Sloe gin")
Ingredient.create(name: "Apple juice")
Ingredient.create(name: "Pineapple juice")
Ingredient.create(name: "Lemon juice")
Ingredient.create(name: "Sugar syrup")
Ingredient.create(name: "Milk")
Ingredient.create(name: "Strawberries")
Ingredient.create(name: "Chocolate syrup")
Ingredient.create(name: "Yoghurt")
Ingredient.create(name: "Mango")
Ingredient.create(name: "Ginger")
